extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key"])

type AdminUser @key(fields: "id") {
  id: ID!
  firstname: String!
  lastname: String!
  email: String!
  authLevel: Int!
}

input CreateAdminUserInput {
  firstname: String!
  lastname: String!
  email: String!
  password: String!
  authLevel: Int!
}

input UpdateAdminUserInput {
  id: ID!
  firstname: String
  lastname: String
  email: String
  password: String
  authLevel: Int
}

type Query {
  adminUsers: [AdminUser!]!
  adminUser(id: ID!): AdminUser
  byEmailAndPassword(email: String!, password: String!): AdminUser
}

type Mutation {
  createAdminUser(createAdminUserInput: CreateAdminUserInput!): AdminUser!
  updateAdminUser(updateAdminUserInput: UpdateAdminUserInput!): AdminUser
  removeAdminUser(id: ID!): AdminUser
}